### ISSUE TITLE
PhantomPath

### ISSUE THREAD

**Issue by mderrick** [jmervine/phapper#1]
Hey,

I have been playing around with your node-yslow repo in my spare time and so far so good!

I wondered if you had time to fix this with Phapper. Right now the phpath.js contains this:

```
module.exports.phantomjs = '/home/jmervine/Development/phapper/lib/phantom/bin/phantomjs';
```

Is there an option I can pass to Phapper so that we can pass through a new bin path from node-yslow. Right now I am changing it manually to get things working. I can see a comment saying this is only required for testing but modifying the prototype is not working.

Am I missing something?

Thanks!

**Comment by jmervine** [comment]
@mderrick The path in this file is actually overwritten at install time here: https://github.com/jmervine/phapper/blob/master/scripts%2Finstall.sh#L21
