### ISSUE TITLE
Won't work on Node >0.10

### ISSUE THREAD

**Issue by igorsantos07** [jmervine/phapper#2]
As per this execSync issue, the package refuses to compile on Node versions higher than 0.10 or io.js.

It is suggested to upgrade to `exec-sync` instead. Do you think it's possible?
I'm collaborating on a project that depends on yslowjs and it's not working properly on newer node versions...

**Comment by jmervine** [comment]
I don't have much time to look at this right now, but am happy to review a pull request on the short term.

**Comment by igorsantos07** [comment]
this seems to be causing weirder issues with usage of projects through `supervisord`. It seems node 0.12 already sports execSync, so I'll be sending a PR that I hope would work :)

**Comment by jmervine** [comment]
It's been a while since I've looked at this. A PR would be welcome!

**Comment by igorsantos07** [comment]
There's already one! Take a look at #3 :)

**Comment by jmervine** [comment]
I will. I'm on a business trip this week, so maybe not right away though.
Thanks!
