### ISSUE TITLE
Phapper doesn't download phantomjs-1.9.8-linux-x86_64.tar.bz2

### ISSUE THREAD

**Issue by alphara** [jmervine/phapper#4]
Hey,

I have error during the installation node_modules through: npm install

```
uncaughtException: Cannot find module '/alphara/node_modules/yslowjs/node_modules/phapper/lib/phpath'
```

This happened cause phpath.js has not been generated. It's cause phantomjs was not installed.

> phapper@0.1.11 install /alphara/node_modules/yslowjs/node_modules/phapper
> node install.js

```
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Decompressing phantomjs-1.9.8-linux-x86_64.tar.bz2...
tar (child): phantomjs-1.9.8-linux-x86_64.tar.bz2: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Error occured decompressing phantomjs-1.9.8-linux-x86_64.tar.bz2.
```

wget downloads this file
`wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2`

But curl doesn't download the file
`curl -O https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2`

**Comment by JustFly1984** [comment]
Confirming the issue on my local mac. Worst thing that on deploy to dev server there is no proper exit code by NPM, so deploy has been failed, and server gives 502!

**Comment by jmervine** [comment]
@alphara Thanks! I saw your PR as well. I'm either going to have to fix `0.x` support or remove it, so it might take me a day or two to get it implement.

**Comment by alphara** [comment]
Good @jmervine

**Comment by alphara** [comment]
Also waiting update version of phapper in node-yslowjs to use last changes.

**Comment by jmervine** [comment]
I'm having issues getting the phantom binary to extract consistently. I'm considering EOLing this lib and reworking node-yslow to use https://www.npmjs.com/package/phantom. My issue with that lib has always been that it will download phantom even if it's already installed, hence me creating this one. Sadly I don't have much time to look at these libs, nor am I doing much work in node -- so I feel a little out of date on recent updates and such. :/

**Comment by talfstad** [comment]
Can you please push an update on this asap! it's a tiny update to fix the download link ;) thanks for taking the time to develop this package for us.

WORKAROUND TO SAVE YOU GUYS A LOT OF TIME DEBUGGING THIS:
NOTE: execute these instructions before running `npm install phaper`
1. `mkdir -p /tmp/phapper.temp`
2. `cd /tmp/phapper.temp`
3. `curl -sLO "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip"`

we mitigate the bad download link by pre-downloading the correct file.
phappers install script will then go "oh cool we already have it" and not try to download it again.

**Comment by jmervine** [comment]
If you're experiencing this issue, please install version 0.2.0 for phantom 1.9.7...

```
npm install phapper@0.2.0
```

Otherwise, use the latest version...

```
npm install phapper
```
